version: '3.8'

services:


  gen-req:
    image: pip-gen-req
    build:
      context: .
      dockerfile: req.dockerfile
      args:
        IMAGE: ${BASE_IMAGE}
        HOME: ${REQ_HOME}
    volumes:
      - $PWD/..:${REQ_HOME}
    command: sh -c "pip-compile requirements.in -o requirements.txt"
