name: Publish

on:
  push:
    tags: releases/[1-9]+.[0-9]+.[0-9]+
    branches: [ stable ]

jobs:

  Publish:
    runs-on: ubuntu-latest

    env:
      ANACONDA_TOKEN: ${{secrets.ANACONDA_TOKEN}}
      ANACONDA_USER: ${{secrets.ANACONDA_USER}}

    steps:
    - uses: actions/checkout@v2
    - uses: docker://continuumio/miniconda3

    - name: Updating conda
      run: conda update --all -y

    - name: Installing make
      run: conda install -y make

    - name: Building package
      run: |
        cd ci
        make conda-build

    - name: Testing package
      run: |
        cd ci
        make conda-test

    - name: Converting to other platforms
      run: |
        cd ci
        make conda-convert

    - name: Uploading to anaconda
      run: |
        cd ci
        make conda-publish
