version: '3.8'

x-image-build:
   &default-image-build
    image: ${PACKAGE}-conda
    build:
      context: ../..
      args:
        HOME: ${HOMEDIR}
        IMAGE: ${BASE_IMAGE}
      dockerfile: ci/docker/build.dockerfile

x-image-check:
   &default-image-check
    image: ${PACKAGE}-check
    build:
      context: ../..
      args:
        PKG: ${PACKAGE}
        HOME: ${HOMEDIR}
        IMAGE: ${BASE_IMAGE}
      dockerfile: ci/docker/check.dockerfile

x-image-test:
   &default-image-test
    image: ${PACKAGE}-test
    build:
      context: ../..
      args:
        PKG: ${PACKAGE}
        HOME: ${HOMEDIR}
        IMAGE: ${BASE_IMAGE}
      dockerfile: ci/docker/test.dockerfile

x-image-run:
   &default-image-run
    image: ${PACKAGE}-run
    build:
      context: ../..
      args:
        PKG: ${PACKAGE}
        HOME: ${HOMEDIR}
        IMAGE: ${BASE_IMAGE}
      dockerfile: ci/docker/run.dockerfile

x-volumes:
    &default-volumes
    volumes:
      - $PWD/..:${HOMEDIR}:ro
      - conda_build:${CONDA_BLD_PATH}
    tmpfs:
      - /var/tmpfs

services:

  clean:
    image: alpine
    <<: *default-volumes
    working_dir: ${HOMEDIR}/ci
    command: scripts/conda-clean_env.sh

  build:
    <<: *default-image-build
    <<: *default-volumes
    command: scripts/conda-build.sh

  test:
    <<: *default-image-build
    <<: *default-volumes
    command: scripts/conda-test.sh

  convert:
    <<: *default-image-build
    <<: *default-volumes
    command: scripts/conda-convert.sh

  publish:
    <<: *default-image-build
    <<: *default-volumes
    command: scripts/conda-publish.sh

  flake1:
    <<: *default-image-check
    <<: *default-volumes
    command: ci/scripts/flake_light.sh

  flake:
    <<: *default-image-check
    <<: *default-volumes
    command: ci/scripts/flake.sh

  bandit:
    <<: *default-image-check
    <<: *default-volumes
    command: ci/scripts/bandit.sh

  pytest:
    <<: *default-image-test
    command: bash ci/pytest/cmd.sh

  run:
    <<: *default-image-run

volumes:
  conda_build:
    name: ${PACKAGE}_conda_build
