name: Qodana
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - master
      - stable
      - dev
      - 'releases/*'
  push:
    branches:
      - main
      - master
      - stable
      - dev
      - 'releases/*'
    paths:
      - '**.py'

jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Qodana
        uses: JetBrains/qodana-action@v2024.3
        with:
          results-dir: qodana-results
          cache-dir: qodana-cache
          use-caches: true
          upload-result: true  # Uploads the results as an artifact
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pr-mode: true