name: Publish

on:
  push:
    tags: releases/[1-9]+.[0-9]+.[0-9]+
    branches: [ stable ]

jobs:

  Conda:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: docker://continuumio/miniconda3

    - name: Updating conda
      run: conda update --all -y

    - name: Installing conda-build
      run: conda install -y conda-build

    - name: Installing make
      run: conda install -y make

    - name: Building package
      run: |
        cd ci
        make build

    - name: Testing package
      run: |
        cd ci
        make test

    - name: Converting to other platforms
      run: |
        cd ci
        make convert

    - name: Uploading to anaconda
      run: |
        cd ci
        make publish
