# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Publish

on:
  push:
    branches: [ stable ]
    paths:
      - 'RELEASE'

jobs:

  PyPi:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        pip install setuptools wheel twine
    - name: Build
      run: |
        python setup.py sdist bdist_wheel
    - name: Upload
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        twine upload dist/*

  Conda:
    runs-on: ubuntu-latest
    container: docker://continuumio/anaconda3
    steps:
    - name: Build
      run: |
        python bdist_conda
    - name: Upload
      env:
        CONDA_TOKEN: ${{ secrets.CONDA_TOKEN }}
      run: |
        anaconda upload --user brsynth --token ${CONDA_TOKEN} /opt/conda/conda-bld/linux-64/*.tar.bz2
