name: Publish

on:
  push:
    tags: releases/[1-9]+.[0-9]+.[0-9]+
    branches: [ stable ]

jobs:

  Conda:
    runs-on: ubuntu-latest

    env:
      ANACONDA_TOKEN: ${{secrets.ANACONDA_TOKEN}}
      ANACONDA_USER: ${{secrets.ANACONDA_USER}}

    steps:
    - uses: actions/checkout@v2
    - uses: docker://continuumio/anaconda3

    - name: Updating anaconda environment
      run: conda update --all -y

    - name: Installing make
      run: conda -y make

    - name: Building package
      run: |
        cd ci
        make build

    - name: Testing package
      run: |
        cd ci
        make test

    - name: Converting to other platforms
      run: |
        cd ci
        make convert

    - name: Uploading to anaconda
      run: |
        cd ci
        make publish
