# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Publish

on:
  push:
    branches: [ stable ]
    paths:
      - 'rrparser/**'
      - 'setup.py'
      - 'README.md'

jobs:

  pypi:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        pip install setuptools wheel twine
    - name: Build and publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        python setup.py sdist bdist_wheel
        twine upload dist/*

  conda:
    runs-on: ubuntu-latest
    container: docker://continuumio/anaconda3
    steps:
    - name: Build and Publish
      env:
        CONDA_TOKEN: ${{ secrets.CONDA_TOKEN }}
        PACKAGE: rrparser
      run: |
        conda skeleton pypi ${PACKAGE}
        conda config --set anaconda_upload yes
        conda build --user brsynth --token ${CONDA_TOKEN} ${PACKAGE}
