name: Publish

on:
  push:
    tags: releases/[1-9]+.[0-9]+.[0-9]+
    branches: [ stable ]

jobs:

  Conda:
    runs-on: ubuntu-latest

    env:
      ANACONDA_TOKEN: ${{secrets.ANACONDA_TOKEN}}
      ANACONDA_USER: ${{secrets.ANACONDA_USER}}

    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v1
      with:
        activate-environment: build_env
        auto-update-conda: true
        environment-file: recipe/conda_build_env.yaml
        miniconda-version: "latest"
        auto-activate-base: false

    - name: Set up environment
      run: |
        cd ci
        source .env
        mkdir -p ${CONDA_BLD_PATH}

    - name: Build conda package
      shell: bash -l {0}
      run: ./scripts/conda-build.sh

    - name: Test conda package
      shell: bash -l {0}
      run: ./scripts/conda-test.sh

    - name: Convert to other platforms
      shell: bash -l {0}
      run: ./scripts/conda-convert.sh

    - name: Upload to anaconda
      shell: bash -l {0}
      run: ./scripts/conda-publish.sh
