# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test suite

on:

  push:
    branches: [ master, dev ]
    paths-ignore:
      - 'RELEASE*'
      - 'README*'
      - 'LICENSE*'
      - 'recipe'
      - 'docs'
      - '.github'
      - '!.github/workflows/test*'
  pull_request:
    branches: [ master ]

jobs:

  Test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: docker://continuumio/anaconda3

    - name: Updating anaconda environment
      run: conda update --all -y

    - name: Installing make
      run: apt-get update && apt-get install -y make

    - name: Building package
      run: |
        cd ci
        make build

    - name: Testing package
      run: |
        cd ci
        make test
