# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test

on:

  push:
    branches: [ main, master, dev ]
    paths:
      - '**.py'
  pull_request:
    branches: [ main, master ]

jobs:

  Test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: docker://continuumio/miniconda3

    - name: Updating conda
      run: conda update --all -y

    - name: Installing make
      run: conda install -y make

    - name: Testing package
      run: |
        cd ci
        make test-buildenv env=test
        conda run -n test make test
