# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Test (import)


on:
  push:
    branches: [ master ]
    paths:
      - .github/workflows/test-import.yml
      - 'RELEASE.md'
      - 'setup.py'

jobs:

  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8]

    steps:

    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Import module from GIT
      run: |
        pip install git+https://github.com/brsynth/RRulesParser
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        # virtual env (needed for importing custom module)
        pip install -e .

    - name: Test CLI call
      run: |
        python -m rrparser --help
